version: '3.5'

services:
  node-front:
    image: node:18.2.0
    container_name: node-front
    working_dir: /var/www/
    command: /bin/bash -c "yarn && yarn dev"
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/